CREATE TABLE users (
	userid		INT UNSIGNED PRIMARY KEY NOT NULL UNIQUE,
	username	VARCHAR(80) NOT NULL,
	password	CHAR(32) NOT NULL,
	created		TIMESTAMP NOT NULL,
	lastlogin	TIMESTAMP
)

CREATE TABLE profiles (
	profileid	INT UNSIGNED PRIMARY KEY NOT NULL UNIQUE,
	userid		INTEGER NOT NULL REFERENCES users (userid),
	displayname	VARCHAR(80),
	primaryemail	VARCHAR(255) NOT NULL
}

